import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import { useState } from "react";

export default function Home({ userData, todoeData }) {
  // const [currentPage, setCurrentPage] = useState(1);
  // const [itemsPerPage, setItemsPerPage] = useState(5);
  // const indexOfLastItem = currentPage * itemsPerPage;
  // const indexOfFirstItem = indexOfLastItem - itemsPerPage;

  // const paginate = (pageNumber) => setCurrentPage(pageNumber);
  return (
    <>
      <Head>
        <title>Sample Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main todo={todoeData} user={userData} />
      </div>
    </>
  );
}
Home.getInitialProps = async function (context) {
  // const { id } = context.query;

  const [userData, todoeData] = await Promise.all([
    fetch(`https://jsonplaceholder.typicode.com/users`).then((r) => r.json()),
    fetch(`https://jsonplaceholder.typicode.com/todos`).then((r) => r.json()),
  ]);

  return { userData, todoeData };
};
