import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
// import styles from "../styles/Home.module.css";

export default function Home({ userData, todoeData }) {
  // console.log(userData);
  // console.log(todoeData);

  return (
    <>
      <Head>
        <title>Sample Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main todo={todoeData} user={userData} />
      </div>
    </>
  );
}
Home.getInitialProps = async function (context) {
  // const { id } = context.query;

  const [userData, todoeData] = await Promise.all([
    fetch(`https://jsonplaceholder.typicode.com/users`).then((r) => r.json()),
    fetch(`https://jsonplaceholder.typicode.com/todos`).then((r) => r.json()),
  ]);

  return { userData, todoeData };
};
// console.log(userData);
